name: 'Publish to nuget'

on:
  release:
    types: [published]

env:
  TARGET_PROJECT_PATH: src/kr.bbon.Services/
  TARGET_PROJECT_FILE: kr.bbon.Services.csproj

jobs:
  publish:
    name: 'Publish to nuget'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

#       - name: Test
#         run: dotnet test --no-build --verbosity normal

      - name: Get version 
        uses: bbonkr/get-version-action@v1.0.3
        id: get_version
        with:
          project: "${{ env.TARGET_PROJECT_PATH }}${{ env.TARGET_PROJECT_FILE }}" 

      - name: Check git tag 
        uses: bbonkr/git-tag-check-action@v1.0.5
        id: git_tag_check
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          tag: 'v${{ steps.get_version.outputs.version }}'

      - name: publish 
        id: publish_nuget
        if: ${{ steps.git_tag_check.outputs.tag != '' }}
        working-directory: ${{ env.TARGET_PROJECT_PATH }}
        run: |
          dotnet pack -c Release -o .
          dotnet nuget push *.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Notify to slack
        uses: 8398a7/action-slack@v3
        with:
          job_name: publish
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always() # Pick up events even if the job fails or is canceled. 

      - name: Notify to Microsoft Teams
        uses: skitionek/notify-microsoft-teams@master
        if: always()
        with:
          webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
          needs: ${{ toJson(needs) }}
          job: ${{ toJson(job) }}
          steps: ${{ toJson(steps) }}
